package:
  name: multiphonon
  version: "0.1.1a1"

source:
  git_rev: master
  git_url: https://github.com/sns-chops/multiphonon.git

requirements:
  build:
    - python
    - numpy
    - histogram
    - scipy

  run:
    - python
    - numpy
    - histogram
    - scipy
    - pytest
    - mcvine
    - mantid-framework

test:
  imports:
    - multiphonon
  

about:
  home: 
  license:
  license_file:
